services:
  downloader-api:
    environment:
      AllowedCorsOrigins__0: "http://localhost:3000"
    volumes:
      - /Users/haas/Sources/Haas.Media/data:/data
  web:
    environment:
      NEXT_PUBLIC_API_DOWNLOADER_URL: "http://localhost:8000"