services:
  haas-media-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  mongodb:
    image: "docker.io/library/mongo:8.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    expose:
      - "27017"
    networks:
      - "aspire"
  downloader-api:
    image: "${DOWNLOADER_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8000"
      ConnectionStrings__haas-media-db: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/haas-media-db?authSource=admin&authMechanism=SCRAM-SHA-256"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
      TMDB_API_KEY: "${TMDB_API_KEY}"
      DATA_DIRECTORY: "/data"
      FFMPEG_BINARY: "/ffmpeg"
      AllowedCorsOrigins__0: "http://web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://haas-media-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "downloader-api"
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: "service_started"
    networks:
      - "aspire"
  web:
    image: "${WEB_IMAGE}"
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_DOWNLOADER_URL: "http://downloader-api:8000"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
      AUTH0_SECRET: "${AUTH0_SECRET}"
      AUTH0_BASE_URL: "${AUTH0_BASE_URL}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
      AUTH0_ISSUER_BASE_URL: "https://${AUTH0_DOMAIN}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://haas-media-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "web"
    ports:
      - "3000:3000"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
